name: "Mushu - AI Code Analyst"
description: "🐉 Analyze tickets and explore codebases using Claude AI"
author: "Zafran"
branding:
  icon: "search"
  color: "red"

inputs:
  ticket_key:
    description: "Issue ticket key (e.g., PROJ-123)"
    required: true
  ticket_summary:
    description: "Issue ticket summary/title"
    required: true
  ticket_description:
    description: "Issue ticket description"
    required: false
    default: ""
  analysis_mode:
    description: "Analysis mode: bug, explore, or fix"
    required: true
    default: "bug"
  anthropic_api_key:
    description: "Anthropic API key for Claude"
    required: true
  github_token:
    description: "GitHub token (required for fix mode)"
    required: false
    default: ""
  base_branch:
    description: "Base branch for PRs (default: main)"
    required: false
    default: "main"
  custom_instructions:
    description: "Additional instructions to append to the prompt"
    required: false
    default: ""
  timeout_minutes:
    description: "Timeout for Claude analysis in minutes"
    required: false
    default: "15"
  pr_draft:
    description: "Create PR as draft (default: true)"
    required: false
    default: "true"
  pr_labels:
    description: "Comma-separated labels to add to created PRs"
    required: false
    default: "mushu,automated"

outputs:
  analysis:
    description: "Claude analysis result"
    value: ${{ steps.claude.outputs.result }}
  pr_url:
    description: "URL of created PR (fix mode only)"
    value: ${{ steps.create-pr.outputs.pull-request-url }}
  pr_number:
    description: "Number of created PR (fix mode only)"
    value: ${{ steps.create-pr.outputs.pull-request-number }}
  has_changes:
    description: "Whether code changes were made (fix mode)"
    value: ${{ steps.commit.outputs.has_changes }}
  branch_name:
    description: "Name of the created branch (fix mode)"
    value: ${{ steps.branch.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        echo "🐉 Mushu - AI Code Analyst"
        echo "=========================="
        
        if [[ ! "${{ inputs.analysis_mode }}" =~ ^(bug|explore|fix)$ ]]; then
          echo "::error::Invalid analysis mode: ${{ inputs.analysis_mode }}"
          exit 1
        fi
        
        if [[ "${{ inputs.analysis_mode }}" == "fix" && -z "${{ inputs.github_token }}" ]]; then
          echo "::error::github_token is required for fix mode"
          exit 1
        fi
        
        echo "✓ Mode: ${{ inputs.analysis_mode }}"
        echo "✓ Ticket: ${{ inputs.ticket_key }}"

    - name: Build prompt
      id: prompt
      shell: bash
      run: |
        PROMPT_FILE="${{ github.action_path }}/prompts/${{ inputs.analysis_mode }}.md"
        
        if [[ ! -f "$PROMPT_FILE" ]]; then
          echo "::error::Prompt file not found: $PROMPT_FILE"
          exit 1
        fi
        
        PROMPT=$(cat "$PROMPT_FILE")
        PROMPT="${PROMPT//\{\{TICKET_KEY\}\}/${{ inputs.ticket_key }}}"
        PROMPT="${PROMPT//\{\{TICKET_SUMMARY\}\}/${{ inputs.ticket_summary }}}"
        
        DESCRIPTION='${{ inputs.ticket_description }}'
        [[ -z "$DESCRIPTION" ]] && DESCRIPTION="No description provided"
        
        {
          echo "prompt<<MUSHU_EOF"
          echo "$PROMPT"
          echo ""
          echo "## Description"
          echo "$DESCRIPTION"
          if [[ -n "${{ inputs.custom_instructions }}" ]]; then
            echo ""
            echo "## Additional Instructions"
            echo "${{ inputs.custom_instructions }}"
          fi
          echo "MUSHU_EOF"
        } >> $GITHUB_OUTPUT

    - name: Determine tools
      id: tools
      shell: bash
      run: |
        if [[ "${{ inputs.analysis_mode }}" == "fix" ]]; then
          echo "allowed=View,GlobTool,GrepTool,BatchTool,Edit,Write" >> $GITHUB_OUTPUT
        else
          echo "allowed=View,GlobTool,GrepTool,BatchTool" >> $GITHUB_OUTPUT
        fi

    - name: Create branch
      id: branch
      if: inputs.analysis_mode == 'fix'
      shell: bash
      run: |
        SAFE_KEY=$(echo "${{ inputs.ticket_key }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
        BRANCH_NAME="mushu/${SAFE_KEY}"
        
        git config user.name "Mushu Bot"
        git config user.email "mushu-bot@users.noreply.github.com"
        
        if git show-ref --verify --quiet "refs/heads/$BRANCH_NAME" 2>/dev/null; then
          BRANCH_NAME="${BRANCH_NAME}-$(date +%s)"
        fi
        
        git checkout -b "$BRANCH_NAME"
        echo "name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "✓ Branch: $BRANCH_NAME"

    - name: Run Claude
      id: claude
      uses: anthropics/claude-code-action@beta
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        prompt: ${{ steps.prompt.outputs.prompt }}
        allowed_tools: ${{ steps.tools.outputs.allowed }}
        timeout_minutes: ${{ inputs.timeout_minutes }}

    - name: Commit changes
      id: commit
      if: inputs.analysis_mode == 'fix'
      shell: bash
      run: |
        if git diff --quiet && git diff --staged --quiet; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "::notice::No code changes made"
        else
          git add -A
          git commit -m "[${{ inputs.ticket_key }}] ${{ inputs.ticket_summary }}" \
                     -m "Automated fix by Mushu AI"
          git push origin "${{ steps.branch.outputs.name }}"
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "✓ Changes committed"
        fi

    - name: Create PR
      id: create-pr
      if: inputs.analysis_mode == 'fix' && steps.commit.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.github_token }}
        branch: ${{ steps.branch.outputs.name }}
        base: ${{ inputs.base_branch }}
        title: "[${{ inputs.ticket_key }}] ${{ inputs.ticket_summary }}"
        body: |
          ## 🐉 Mushu Automated Fix
          
          **Ticket:** ${{ inputs.ticket_key }}
          
          ### Summary
          ${{ inputs.ticket_summary }}
          
          <details>
          <summary>AI Analysis</summary>
          
          ```
          ${{ steps.claude.outputs.result }}
          ```
          </details>
          
          ---
          *Created by [Mushu](https://github.com/liorkesten/mushu). Review before merging.*
        labels: ${{ inputs.pr_labels }}
        draft: ${{ inputs.pr_draft }}

    - name: Summary
      shell: bash
      run: |
        echo ""
        echo "🐉 Analysis Complete"
        echo "==================="
        echo "Ticket: ${{ inputs.ticket_key }}"
        echo "Mode: ${{ inputs.analysis_mode }}"
        if [[ "${{ steps.create-pr.outputs.pull-request-url }}" ]]; then
          echo "PR: ${{ steps.create-pr.outputs.pull-request-url }}"
        fi
