name: "Mushu - GitHub Issues Integration"
description: "📋 Post Mushu analysis results to GitHub Issues"
author: "Zafran"
branding:
  icon: "message-circle"
  color: "purple"

inputs:
  github_token:
    description: "GitHub token with issues write permission"
    required: true
  issue_number:
    description: "GitHub issue number"
    required: true
  analysis:
    description: "Analysis text to post as comment"
    required: true
  analysis_mode:
    description: "Analysis mode that was used: bug, explore, or fix"
    required: true
  pr_url:
    description: "URL of created PR (optional, for fix mode)"
    required: false
    default: ""
  has_changes:
    description: "Whether code changes were made (optional, for fix mode)"
    required: false
    default: ""
  add_labels:
    description: "Labels to add after posting (comma-separated)"
    required: false
    default: ""
  remove_labels:
    description: "Labels to remove after posting (comma-separated)"
    required: false
    default: ""

outputs:
  comment_id:
    description: "ID of the created GitHub comment"
    value: ${{ steps.post.outputs.comment_id }}
  comment_url:
    description: "URL of the created GitHub comment"
    value: ${{ steps.post.outputs.comment_url }}

runs:
  using: "composite"
  steps:
    - name: Post comment
      id: post
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        ANALYSIS: ${{ inputs.analysis }}
        ANALYSIS_MODE: ${{ inputs.analysis_mode }}
        PR_URL: ${{ inputs.pr_url }}
        HAS_CHANGES: ${{ inputs.has_changes }}
      run: |
        set -e
        
        # Build mode indicator
        case "$ANALYSIS_MODE" in
          bug) MODE_LABEL="🐛 Bug Analysis" ;;
          explore) MODE_LABEL="🔍 Exploration" ;;
          fix) MODE_LABEL="🔧 Fix Analysis" ;;
          *) MODE_LABEL="Analysis" ;;
        esac
        
        # Build comment
        COMMENT="## 🐉 Mushu: $MODE_LABEL

<details>
<summary>Click to expand analysis</summary>

\`\`\`
$ANALYSIS
\`\`\`

</details>"
        
        # Add PR link for fix mode
        if [[ "$ANALYSIS_MODE" == "fix" ]]; then
          if [[ "$HAS_CHANGES" == "true" && -n "$PR_URL" ]]; then
            COMMENT+="

---
🔗 **Pull Request:** $PR_URL"
          elif [[ "$HAS_CHANGES" == "false" ]]; then
            COMMENT+="

---
ℹ️ No code changes were needed."
          fi
        fi
        
        COMMENT+="

---
*Generated by [Mushu](https://github.com/liorkesten/mushu)*"
        
        # Post comment
        RESULT=$(gh issue comment "$ISSUE_NUMBER" --body "$COMMENT" --json id,url)
        
        COMMENT_ID=$(echo "$RESULT" | jq -r '.id')
        COMMENT_URL=$(echo "$RESULT" | jq -r '.url')
        
        echo "comment_id=$COMMENT_ID" >> $GITHUB_OUTPUT
        echo "comment_url=$COMMENT_URL" >> $GITHUB_OUTPUT
        echo "✓ Comment posted to issue #$ISSUE_NUMBER"

    - name: Update labels
      if: inputs.add_labels != '' || inputs.remove_labels != ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        ADD_LABELS: ${{ inputs.add_labels }}
        REMOVE_LABELS: ${{ inputs.remove_labels }}
      run: |
        if [[ -n "$ADD_LABELS" ]]; then
          gh issue edit "$ISSUE_NUMBER" --add-label "$ADD_LABELS" || true
          echo "✓ Added labels: $ADD_LABELS"
        fi
        
        if [[ -n "$REMOVE_LABELS" ]]; then
          for label in $(echo "$REMOVE_LABELS" | tr ',' ' '); do
            gh issue edit "$ISSUE_NUMBER" --remove-label "$label" || true
          done
          echo "✓ Removed labels: $REMOVE_LABELS"
        fi

