# Example: Basic Mushu Workflow
# Minimal setup - just analyze tickets, no integrations

name: Mushu
run-name: "ðŸ‰ ${{ inputs.ticket_key }} (${{ inputs.analysis_mode }})"

on:
  workflow_dispatch:
    inputs:
      ticket_key:
        description: "Ticket key (e.g., PROJ-123)"
        required: true
        type: string
      ticket_summary:
        description: "Ticket summary"
        required: true
        type: string
      ticket_description:
        description: "Ticket description"
        required: false
        type: string
        default: ""
      analysis_mode:
        description: "Analysis mode"
        required: true
        type: choice
        options:
          - bug
          - explore
          - fix

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Mushu
        id: mushu
        uses: liorkesten/mushu@v1
        with:
          ticket_key: ${{ inputs.ticket_key }}
          ticket_summary: ${{ inputs.ticket_summary }}
          ticket_description: ${{ inputs.ticket_description }}
          analysis_mode: ${{ inputs.analysis_mode }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output results
        run: |
          echo "## Analysis Results" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.mushu.outputs.analysis }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          
          if [[ -n "${{ steps.mushu.outputs.pr_url }}" ]]; then
            echo "**PR:** ${{ steps.mushu.outputs.pr_url }}" >> $GITHUB_STEP_SUMMARY
          fi
