# Example: Mushu with GitHub Issues
# Auto-analyze issues and post results back as comments

name: Mushu + GitHub Issues
run-name: "ðŸ‰ #${{ github.event.issue.number }}"

on:
  issues:
    types: [opened, labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: mushu-issue-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    # Trigger conditions:
    # - New bug issue
    # - 'mushu' label added (explore mode)
    # - 'mushu-fix' label added (fix mode)
    if: |
      (github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'bug')) ||
      (github.event.action == 'labeled' && github.event.label.name == 'mushu') ||
      (github.event.action == 'labeled' && github.event.label.name == 'mushu-fix')
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine mode
        id: mode
        run: |
          if [[ "${{ contains(github.event.issue.labels.*.name, 'mushu-fix') }}" == "true" ]]; then
            echo "value=fix" >> $GITHUB_OUTPUT
          elif [[ "${{ contains(github.event.issue.labels.*.name, 'bug') }}" == "true" ]]; then
            echo "value=bug" >> $GITHUB_OUTPUT
          else
            echo "value=explore" >> $GITHUB_OUTPUT
          fi

      # Step 1: Run analysis
      - name: Analyze
        id: mushu
        uses: liorkesten/mushu@v1
        with:
          ticket_key: ${{ github.event.issue.number }}
          ticket_summary: ${{ github.event.issue.title }}
          ticket_description: ${{ github.event.issue.body }}
          analysis_mode: ${{ steps.mode.outputs.value }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Post to GitHub Issue
      - name: Post to Issue
        uses: liorkesten/mushu/integrations/github-issues@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          analysis: ${{ steps.mushu.outputs.analysis }}
          analysis_mode: ${{ steps.mode.outputs.value }}
          pr_url: ${{ steps.mushu.outputs.pr_url }}
          has_changes: ${{ steps.mushu.outputs.has_changes }}
          add_labels: mushu-analyzed
          remove_labels: mushu,mushu-fix
